name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build x64
      run: msbuild reshade-screenshot-discord-fix.vcxproj /p:Configuration=Release /p:Platform=x64

    - name: Build Win32
      run: msbuild reshade-screenshot-discord-fix.vcxproj /p:Configuration=Release /p:Platform=Win32

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DiscordHDRFix-Addon
        path: |
          bin/x64/DiscordHDRFix.addon64
          bin/Win32/DiscordHDRFix.addon32

    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/x64/DiscordHDRFix.addon64
          bin/Win32/DiscordHDRFix.addon32
